#!/usr/bin/env bash
set -euo pipefail

: "${CONNECT_BOOTSTRAP_SERVERS:?CONNECT_BOOTSTRAP_SERVERS is required}"
: "${CONNECT_GROUP_ID:?CONNECT_GROUP_ID is required}"
: "${CONNECT_CONFIG_STORAGE_TOPIC:?CONNECT_CONFIG_STORAGE_TOPIC is required}"
: "${CONNECT_OFFSET_STORAGE_TOPIC:?CONNECT_OFFSET_STORAGE_TOPIC is required}"
: "${CONNECT_STATUS_STORAGE_TOPIC:?CONNECT_STATUS_STORAGE_TOPIC is required}"
: "${CONNECT_SASL_JAAS_CONFIG:?CONNECT_SASL_JAAS_CONFIG is required}"

CONNECT_REST_PORT="${CONNECT_REST_PORT:-8083}"
CONNECT_PLUGIN_PATH="${CONNECT_PLUGIN_PATH:-/usr/share/java,/usr/share/confluent-hub-components}"
CONNECT_SECURITY_PROTOCOL="${CONNECT_SECURITY_PROTOCOL:-SASL_SSL}"
CONNECT_SASL_MECHANISM="${CONNECT_SASL_MECHANISM:-SCRAM-SHA-512}"
CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR="${CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR:-2}"
CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR="${CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR:-2}"
CONNECT_STATUS_STORAGE_REPLICATION_FACTOR="${CONNECT_STATUS_STORAGE_REPLICATION_FACTOR:-2}"
CONNECT_OFFSET_FLUSH_INTERVAL_MS="${CONNECT_OFFSET_FLUSH_INTERVAL_MS:-60000}"
CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE="${CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE:-false}"
CONNECT_REST_ADVERTISED_HOST_NAME="${CONNECT_REST_ADVERTISED_HOST_NAME:-${HOSTNAME:-localhost}}"

cat > /tmp/connect-distributed.properties <<EOF
bootstrap.servers=${CONNECT_BOOTSTRAP_SERVERS}
group.id=${CONNECT_GROUP_ID}
config.storage.topic=${CONNECT_CONFIG_STORAGE_TOPIC}
offset.storage.topic=${CONNECT_OFFSET_STORAGE_TOPIC}
status.storage.topic=${CONNECT_STATUS_STORAGE_TOPIC}
config.storage.replication.factor=${CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR}
offset.storage.replication.factor=${CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR}
status.storage.replication.factor=${CONNECT_STATUS_STORAGE_REPLICATION_FACTOR}
offset.flush.interval.ms=${CONNECT_OFFSET_FLUSH_INTERVAL_MS}
key.converter=${CONNECT_KEY_CONVERTER:-org.apache.kafka.connect.storage.StringConverter}
value.converter=${CONNECT_VALUE_CONVERTER:-org.apache.kafka.connect.json.JsonConverter}
value.converter.schemas.enable=${CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE}
plugin.path=${CONNECT_PLUGIN_PATH}
rest.port=${CONNECT_REST_PORT}
rest.advertised.host.name=${CONNECT_REST_ADVERTISED_HOST_NAME}
security.protocol=${CONNECT_SECURITY_PROTOCOL}
sasl.mechanism=${CONNECT_SASL_MECHANISM}
sasl.jaas.config=${CONNECT_SASL_JAAS_CONFIG}
consumer.security.protocol=${CONNECT_SECURITY_PROTOCOL}
consumer.sasl.mechanism=${CONNECT_SASL_MECHANISM}
consumer.sasl.jaas.config=${CONNECT_SASL_JAAS_CONFIG}
producer.security.protocol=${CONNECT_SECURITY_PROTOCOL}
producer.sasl.mechanism=${CONNECT_SASL_MECHANISM}
producer.sasl.jaas.config=${CONNECT_SASL_JAAS_CONFIG}
EOF

exec /opt/kafka/bin/connect-distributed.sh /tmp/connect-distributed.properties