apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "12"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"quote","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"quote","app.kubernetes.io/part-of":"techx-corp","app.kubernetes.io/version":"2.2.0","argocd.argoproj.io/instance":"techx-corp","helm.sh/chart":"techx-corp-0.40.9","opentelemetry.io/name":"quote"},"name":"quote","namespace":"techx-tf4"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"opentelemetry.io/name":"quote"}},"template":{"metadata":{"annotations":{"resource.opentelemetry.io/service.namespace":"techx-corp"},"labels":{"app.kubernetes.io/component":"quote","app.kubernetes.io/name":"quote","app.kubernetes.io/version":"2.2.0","opentelemetry.io/name":"quote"}},"spec":{"containers":[{"env":[{"name":"OTEL_SERVICE_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.labels['app.kubernetes.io/component']"}}},{"name":"OTEL_COLLECTOR_NAME","value":"otel-collector.techx-observability.svc.cluster.local"},{"name":"OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE","value":"cumulative"},{"name":"QUOTE_PORT","value":"8080"},{"name":"OTEL_PHP_AUTOLOAD_ENABLED","value":"true"},{"name":"OTEL_PHP_INTERNAL_METRICS_ENABLED","value":"true"},{"name":"OTEL_EXPORTER_OTLP_ENDPOINT","value":"http://$(OTEL_COLLECTOR_NAME):4318"},{"name":"IPV6_ENABLED","value":"false"}],"image":"511825856493.dkr.ecr.us-east-1.amazonaws.com/techx-corp:8340af1-quote","imagePullPolicy":"IfNotPresent","name":"quote","ports":[{"containerPort":8080,"name":"service"}],"resources":{"limits":{"cpu":"50m","memory":"40Mi"},"requests":{"cpu":"10m","memory":"20Mi"}},"securityContext":{"runAsGroup":33,"runAsNonRoot":true,"runAsUser":33},"volumeMounts":null}],"serviceAccountName":"techx-corp","volumes":null}}}}
    meta.helm.sh/release-name: techx-corp
    meta.helm.sh/release-namespace: techx-tf4
  creationTimestamp: "2026-07-07T18:35:55Z"
  generation: 12
  labels:
    app.kubernetes.io/component: quote
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: quote
    app.kubernetes.io/part-of: techx-corp
    app.kubernetes.io/version: 2.2.0
    argocd.argoproj.io/instance: techx-corp
    helm.sh/chart: techx-corp-0.40.9
    opentelemetry.io/name: quote
  name: quote
  namespace: techx-tf4
  resourceVersion: "2854043"
  uid: 8ba9ad3f-4c1c-4ce3-8aa5-5fa2d819b183
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      opentelemetry.io/name: quote
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-07-09T10:00:20+07:00"
        resource.opentelemetry.io/service.namespace: techx-corp
      labels:
        app.kubernetes.io/component: quote
        app.kubernetes.io/name: quote
        app.kubernetes.io/version: 2.2.0
        opentelemetry.io/name: quote
    spec:
      containers:
      - env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: OTEL_COLLECTOR_NAME
          value: otel-collector.techx-observability.svc.cluster.local
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: cumulative
        - name: QUOTE_PORT
          value: "8080"
        - name: OTEL_PHP_AUTOLOAD_ENABLED
          value: "true"
        - name: OTEL_PHP_INTERNAL_METRICS_ENABLED
          value: "true"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_COLLECTOR_NAME):4318
        - name: IPV6_ENABLED
          value: "false"
        image: 511825856493.dkr.ecr.us-east-1.amazonaws.com/techx-corp:8340af1-quote
        imagePullPolicy: IfNotPresent
        name: quote
        ports:
        - containerPort: 8080
          name: service
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
        securityContext:
          runAsGroup: 33
          runAsNonRoot: true
          runAsUser: 33
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: techx-corp
      serviceAccountName: techx-corp
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-07-14T22:38:24Z"
    lastUpdateTime: "2026-07-15T00:52:07Z"
    message: ReplicaSet "quote-85c74d484b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2026-07-15T11:08:53Z"
    lastUpdateTime: "2026-07-15T11:08:53Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 12
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
