apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"frontend","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"frontend","app.kubernetes.io/part-of":"techx-corp","app.kubernetes.io/version":"2.2.0","argocd.argoproj.io/instance":"techx-corp","helm.sh/chart":"techx-corp-0.40.9","opentelemetry.io/name":"frontend"},"name":"frontend","namespace":"techx-tf4"},"spec":{"ports":[{"name":"tcp-service","port":8080,"targetPort":8080}],"selector":{"opentelemetry.io/name":"frontend"},"type":"ClusterIP"}}
    meta.helm.sh/release-name: techx-corp
    meta.helm.sh/release-namespace: techx-tf4
  creationTimestamp: "2026-07-07T18:35:37Z"
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: techx-corp
    app.kubernetes.io/version: 2.2.0
    argocd.argoproj.io/instance: techx-corp
    helm.sh/chart: techx-corp-0.40.9
    opentelemetry.io/name: frontend
  name: frontend
  namespace: techx-tf4
  resourceVersion: "2572372"
  uid: 3a87b3ef-dfcc-4079-bff2-8fb8b1b638f5
spec:
  clusterIP: 172.20.39.20
  clusterIPs:
  - 172.20.39.20
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-service
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    opentelemetry.io/name: frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
