apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.0.10.81
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-0-10-17.ec2.internal
    targetRef:
      kind: Pod
      name: frontend-f8c85f89c-jc77c
      namespace: techx-tf4
      uid: b4729c7e-0f1c-4644-9fb8-be9a71232039
    zone: us-east-1a
  - addresses:
    - 10.0.11.51
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-0-11-89.ec2.internal
    targetRef:
      kind: Pod
      name: frontend-f8c85f89c-wnf2d
      namespace: techx-tf4
      uid: 9867a61d-ac08-4a4b-816c-4a8aa60580d9
    zone: us-east-1b
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-07-15T11:24:32Z"
    creationTimestamp: "2026-07-07T18:35:37Z"
    generateName: frontend-
    generation: 147
    labels:
      app.kubernetes.io/component: frontend
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: frontend
      app.kubernetes.io/part-of: techx-corp
      app.kubernetes.io/version: 2.2.0
      argocd.argoproj.io/instance: techx-corp
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: techx-corp-0.40.9
      kubernetes.io/service-name: frontend
      opentelemetry.io/name: frontend
    name: frontend-js74m
    namespace: techx-tf4
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: frontend
      uid: 3a87b3ef-dfcc-4079-bff2-8fb8b1b638f5
    resourceVersion: "2860552"
    uid: 6d7bdf0c-2b59-4811-bf47-7f58766bdaf6
  ports:
  - name: tcp-service
    port: 8080
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
