{{- if .Values.prometheus.alertmanager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-smtp-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "techx-corp.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth_password: {{ required "A valid .Values.alertmanagerSmtpPassword is required when alertmanager is enabled!" .Values.alertmanagerSmtpPassword }}
{{- end }}
