{{- range $name, $config := .Values.components }}
{{- if and $config.enabled $config.serviceAccountName }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $config.serviceAccountName }}
  labels:
    app.kubernetes.io/component: {{ $name }}
    app.kubernetes.io/part-of: {{ include "techx-corp.name" $ }}
automountServiceAccountToken: true
{{- end }}
{{- end }}
