{{- range $name, $config := .Values.components }}
{{- if $config.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $config.serviceAccountName | default $name }}
  labels:
    app.kubernetes.io/component: {{ $name }}
    app.kubernetes.io/part-of: {{ include "techx-corp.name" $ }}
automountServiceAccountToken: {{ $config.automountServiceAccountToken | default false }}
{{- end }}
{{- end }}
