{{- if .Values.externalSecrets.enabled }}
{{- range $name, $secret := .Values.externalSecrets.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $name }}
  labels:
    helm.sh/chart: {{ include "techx-corp.chart" $ }}
    app.kubernetes.io/part-of: techx-corp
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/component: secret-management
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: {{ $name }}
    creationPolicy: Owner
  data:
    - secretKey: {{ $secret.secretKey }}
      remoteRef:
        key: {{ $secret.remoteRef }}
{{- end }}
{{- end }}
