{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  labels:
    helm.sh/chart: {{ include "techx-corp.chart" . }}
    app.kubernetes.io/part-of: techx-corp
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: secret-management
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.serviceAccountName }}
{{- end }}
