{{- if .Values.gp3StorageClasses.enabled }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-retain
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: {{ .Values.gp3StorageClasses.provisioner | quote }}
parameters:
  type: gp3
  tagSpecification_1: D18Snapshot=true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: {{ .Values.gp3StorageClasses.allowVolumeExpansion }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-retain
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: {{ .Values.gp3StorageClasses.provisioner | quote }}
parameters:
  type: gp3
  tagSpecification_1: D18Snapshot=true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: {{ .Values.gp3StorageClasses.allowVolumeExpansion }}
{{- end }}
