components:
  load-generator:
    replicas: 0
  accounting:
    resources:
      requests: { cpu: 25m, memory: 160Mi }
      limits: { cpu: 250m, memory: 256Mi }
  fraud-detection:
    resources:
      requests: { cpu: 25m, memory: 256Mi }
      limits: { cpu: 250m, memory: 384Mi }
  kafka:
    resources:
      requests: { cpu: 50m, memory: 576Mi }
      limits: { cpu: 500m, memory: 768Mi }
  postgresql:
    resources:
      requests: { cpu: 25m, memory: 64Mi }
      limits: { cpu: 250m, memory: 192Mi }
  valkey-cart:
    resources:
      requests: { cpu: 20m, memory: 16Mi }
      limits: { cpu: 150m, memory: 64Mi }
