apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: techx-general
spec:
  role: karpenter-node-techx-tf4-cluster
  amiSelectorTerms:
    - alias: al2023@v20260709
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: techx-tf4-cluster
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/node-security-group: techx-tf4-cluster
  tags:
    Owner: CDO_04
    Team: CDO_04
    Project: TF4
    Environment: Phase3
    karpenter.sh/discovery: techx-tf4-cluster
