apiVersion: v1
items:
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"autoscaling/v2","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"checkout","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"checkout","app.kubernetes.io/part-of":"techx-corp","app.kubernetes.io/version":"2.2.0","argocd.argoproj.io/instance":"techx-corp","helm.sh/chart":"techx-corp-0.40.9","opentelemetry.io/name":"checkout"},"name":"checkout","namespace":"techx-tf4"},"spec":{"behavior":{"scaleDown":{"policies":[{"periodSeconds":60,"type":"Pods","value":1}],"stabilizationWindowSeconds":300},"scaleUp":{"policies":[{"periodSeconds":60,"type":"Pods","value":1}],"stabilizationWindowSeconds":0}},"maxReplicas":3,"metrics":[{"resource":{"name":"cpu","target":{"averageUtilization":70,"type":"Utilization"}},"type":"Resource"}],"minReplicas":2,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"checkout"}}}
      meta.helm.sh/release-name: techx-corp
      meta.helm.sh/release-namespace: techx-tf4
    creationTimestamp: "2026-07-13T20:22:51Z"
    labels:
      app.kubernetes.io/component: checkout
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: checkout
      app.kubernetes.io/part-of: techx-corp
      app.kubernetes.io/version: 2.2.0
      argocd.argoproj.io/instance: techx-corp
      helm.sh/chart: techx-corp-0.40.9
      opentelemetry.io/name: checkout
    name: checkout
    namespace: techx-tf4
    resourceVersion: "2801026"
    uid: 322a6419-8c83-4c5c-a827-634ad4799ced
  spec:
    behavior:
      scaleDown:
        policies:
        - periodSeconds: 60
          type: Pods
          value: 1
        selectPolicy: Max
        stabilizationWindowSeconds: 300
      scaleUp:
        policies:
        - periodSeconds: 60
          type: Pods
          value: 1
        selectPolicy: Max
        stabilizationWindowSeconds: 0
    maxReplicas: 3
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
    minReplicas: 2
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: checkout
  status:
    conditions:
    - lastTransitionTime: "2026-07-13T20:23:06Z"
      message: recommended size matches current size
      reason: ReadyForNewScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2026-07-15T06:16:53Z"
      message: the HPA was able to successfully calculate a replica count from cpu
        resource utilization (percentage of request)
      reason: ValidMetricFound
      status: "True"
      type: ScalingActive
    - lastTransitionTime: "2026-07-15T06:54:27Z"
      message: the desired replica count is less than the minimum replica count
      reason: TooFewReplicas
      status: "True"
      type: ScalingLimited
    currentMetrics:
    - resource:
        current:
          averageUtilization: 2
          averageValue: 1m
        name: cpu
      type: Resource
    currentReplicas: 2
    desiredReplicas: 2
    lastScaleTime: "2026-07-15T06:49:11Z"
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"autoscaling/v2","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"currency","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"currency","app.kubernetes.io/part-of":"techx-corp","app.kubernetes.io/version":"2.2.0","argocd.argoproj.io/instance":"techx-corp","helm.sh/chart":"techx-corp-0.40.9","opentelemetry.io/name":"currency"},"name":"currency","namespace":"techx-tf4"},"spec":{"behavior":{"scaleDown":{"policies":[{"periodSeconds":60,"type":"Pods","value":1}],"stabilizationWindowSeconds":300},"scaleUp":{"policies":[{"periodSeconds":60,"type":"Pods","value":1}],"stabilizationWindowSeconds":0}},"maxReplicas":3,"metrics":[{"resource":{"name":"cpu","target":{"averageUtilization":70,"type":"Utilization"}},"type":"Resource"}],"minReplicas":2,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"currency"}}}
    creationTimestamp: "2026-07-15T08:24:32Z"
    labels:
      app.kubernetes.io/component: currency
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: currency
      app.kubernetes.io/part-of: techx-corp
      app.kubernetes.io/version: 2.2.0
      argocd.argoproj.io/instance: techx-corp
      helm.sh/chart: techx-corp-0.40.9
      opentelemetry.io/name: currency
    name: currency
    namespace: techx-tf4
    resourceVersion: "2800941"
    uid: 8d23c1b9-23d1-4478-86b6-34ff3b453816
  spec:
    behavior:
      scaleDown:
        policies:
        - periodSeconds: 60
          type: Pods
          value: 1
        selectPolicy: Max
        stabilizationWindowSeconds: 300
      scaleUp:
        policies:
        - periodSeconds: 60
          type: Pods
          value: 1
        selectPolicy: Max
        stabilizationWindowSeconds: 0
    maxReplicas: 3
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
    minReplicas: 2
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: currency
  status:
    conditions:
    - lastTransitionTime: "2026-07-15T08:24:47Z"
      message: recommended size matches current size
      reason: ReadyForNewScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2026-07-15T08:25:32Z"
      message: the HPA was able to successfully calculate a replica count from cpu
        resource utilization (percentage of request)
      reason: ValidMetricFound
      status: "True"
      type: ScalingActive
    - lastTransitionTime: "2026-07-15T08:25:02Z"
      message: the desired count is within the acceptable range
      reason: DesiredWithinRange
      status: "False"
      type: ScalingLimited
    currentMetrics:
    - resource:
        current:
          averageUtilization: 72
          averageValue: 54m
        name: cpu
      type: Resource
    currentReplicas: 2
    desiredReplicas: 2
    lastScaleTime: "2026-07-15T08:24:47Z"
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"autoscaling/v2","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"frontend","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"frontend","app.kubernetes.io/part-of":"techx-corp","app.kubernetes.io/version":"2.2.0","argocd.argoproj.io/instance":"techx-corp","helm.sh/chart":"techx-corp-0.40.9","opentelemetry.io/name":"frontend"},"name":"frontend","namespace":"techx-tf4"},"spec":{"behavior":{"scaleDown":{"policies":[{"periodSeconds":60,"type":"Pods","value":1}],"stabilizationWindowSeconds":300},"scaleUp":{"policies":[{"periodSeconds":60,"type":"Pods","value":1}],"stabilizationWindowSeconds":0}},"maxReplicas":3,"metrics":[{"resource":{"name":"cpu","target":{"averageUtilization":70,"type":"Utilization"}},"type":"Resource"}],"minReplicas":2,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"frontend"}}}
      meta.helm.sh/release-name: techx-corp
      meta.helm.sh/release-namespace: techx-tf4
    creationTimestamp: "2026-07-13T20:22:51Z"
    labels:
      app.kubernetes.io/component: frontend
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: frontend
      app.kubernetes.io/part-of: techx-corp
      app.kubernetes.io/version: 2.2.0
      argocd.argoproj.io/instance: techx-corp
      helm.sh/chart: techx-corp-0.40.9
      opentelemetry.io/name: frontend
    name: frontend
    namespace: techx-tf4
    resourceVersion: "2801027"
    uid: 10c693f0-a1ce-4505-8b27-851ad7bac8df
  spec:
    behavior:
      scaleDown:
        policies:
        - periodSeconds: 60
          type: Pods
          value: 1
        selectPolicy: Max
        stabilizationWindowSeconds: 300
      scaleUp:
        policies:
        - periodSeconds: 60
          type: Pods
          value: 1
        selectPolicy: Max
        stabilizationWindowSeconds: 0
    maxReplicas: 3
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
    minReplicas: 2
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: frontend
  status:
    conditions:
    - lastTransitionTime: "2026-07-13T20:23:06Z"
      message: recommended size matches current size
      reason: ReadyForNewScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2026-07-15T05:45:06Z"
      message: the HPA was able to successfully calculate a replica count from cpu
        resource utilization (percentage of request)
      reason: ValidMetricFound
      status: "True"
      type: ScalingActive
    - lastTransitionTime: "2026-07-15T07:22:44Z"
      message: the desired replica count is less than the minimum replica count
      reason: TooFewReplicas
      status: "True"
      type: ScalingLimited
    currentMetrics:
    - resource:
        current:
          averageUtilization: 15
          averageValue: 15m
        name: cpu
      type: Resource
    currentReplicas: 2
    desiredReplicas: 2
    lastScaleTime: "2026-07-15T07:22:29Z"
kind: List
metadata:
  resourceVersion: ""
